replicaCount: 1
image:
  repository: '{{commons.repository}}/{{commons.repositoryNamespace}}'
  tag:
    test-src: 16f1335a529eb2d77a848111e911507bd24cfa04
  pullPolicy: IfNotPresent
nameOverride: ''
fullnameOverride: ''
service:
  type: ClusterIP
  port: 8088
ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: acs-ingress
  paths:
  - /
  hosts:
  - chart-example.local
  tls: []
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
