type: chart
name: test-chart # release name
id: test-chart
include:
  - id: test-src
    git_url: https://github.com/carlos-lee/test-src.git
dependencies:
  - type: zookeeper
    id: default
  - type: redis
    id: default
  - type: rocketmq
    id: default

