type: chart
name: test-chart # release name
id: test-chart
include:
  - id: test-src
    git_url: https://github.com/carlos-lee/test-src.git
dependencies:
  - type: zookeeper
    id: default
  - type: redis
    id: default
  - type: rocketmq
    id: default


##!/bin/sh
#cd test-src
#make build
#commit_id=`git rev-parse HEAD`
#project_dir=`pwd`
#project_name=${project_dir##*/}
#image_name=192.168.0.201:5000/admin/${project_name}:${commit_id}
#docker build -t $image_name .
#docker push $image_name
#cd ../test-chart
#sed -i "9s:.*:${commit_id}:g" values.yml
